# Generated by Django 5.2.4 on 2025-07-19 15:02

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_reportfile_report_reportfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to=reports.models.user_upload_path),
        ),
    ]
