# Generated by Django 5.2.4 on 2025-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='original_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
