# Generated by Django 5.2.4 on 2025-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_medicalcase_age_alter_medicalcase_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcase',
            name='aggregated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
